Add output struct for scs generation
ostis-ai/ts-sc-client pull request #26
Opened 2023-01-18 13:13 UTC by SHtress

2023-01-19 13:17 UTC, NikitaZotov requested changes

2023-01-19 13:17 UTC, NikitaZotov commented on src/ScClient.ts
> +        if(typeof scsString === "string")
```suggestion
        if (typeof scsString === "string")
```

2023-01-19 13:17 UTC, NikitaZotov commented on src/ScClient.ts
> +        if(typeof scsString === "string")
Format all please

2023-01-19 13:17 UTC, NikitaZotov commented on src/ScClient.ts
> +        else{
Too

2023-01-19 13:17 UTC, NikitaZotov commented on src/ScClient.ts
> +          return {scs: scsString.scs, outputStructure: scsString.outputStructure?.value as number}
If scsString.outputStructure is null client send this null to sc-server. Client must send 0, not null

2023-01-19 13:17 UTC, NikitaZotov commented on tests/scClient.test.ts
> +             outputStructure: 0},
Can we don't point outputStructure value? Don't change this test. Tests static state shows backward compatibility

2023-01-19 13:17 UTC, NikitaZotov commented on tests/scClient.test.ts
> +  test("createElementsBySCsWithOutputStruct", async () => {
Add more test with different params passing

2023-01-23 18:53 UTC, KovalM approved these changes

2023-01-25 09:20 UTC, NikitaZotov commented on tests/scClient.test.ts
> +            outputStructure: 0
output_structure

2023-01-25 11:50 UTC, aleksgrin approved these changes

2023-01-25 11:50 UTC, aleksgrin commented on src/ScClient.ts
> +        else {
Можно убрать else. Все равно return в предыдущем if

2023-01-25 11:50 UTC, aleksgrin commented on src/ScClient.ts
> +          return { scs: scsString.scs, output_structure: scsString.output_structure?.value as number }
Странно, что тут надо делать as. Вроде в типе же указано, что output_structure будет всегда

2023-01-25 12:04 UTC, NikitaZotov approved these changes

2023-01-26 08:15 UTC, merged